"""initial migration

Revision ID: 6fb1dcc7add7
Revises: 
Create Date: 2024-09-24 14:48:18.486689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb1dcc7add7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wrestler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('weight_class', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('wrestler1_id', sa.Integer(), nullable=False),
    sa.Column('wrestler2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('win_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['winner_id'], ['wrestler.id'], ),
    sa.ForeignKeyConstraint(['wrestler1_id'], ['wrestler.id'], ),
    sa.ForeignKeyConstraint(['wrestler2_id'], ['wrestler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('wrestler')
    # ### end Alembic commands ###
